import markedSource from 'marked?raw'
import zipSource from '../../../node_modules/fflate/umd/index.js?raw'
import menuStyles from '../../styles/popup-menu.css?raw'
import { projectShareBrowser } from './browser'
import type { ProjectSnapshot } from './types'
import type { ProjectPresentation } from './presentation'
import { normalizeShareTitle } from './title'

export interface ProjectBundleOptions { title?: string; presentation?: ProjectPresentation; archiveUrl?: string; publicationPending?: boolean }

/** One self-contained static page for either publication stage. */
export function buildProjectBundle(snapshot: ProjectSnapshot, feedbackUrl: string, options: ProjectBundleOptions = {}): string {
  const endpoint = new URL(feedbackUrl)
  if(!['http:','https:'].includes(endpoint.protocol) || endpoint.username || endpoint.password) throw new Error('Invalid feedback endpoint')
  if(options.archiveUrl) {
    const archive=new URL(options.archiveUrl)
    if(archive.origin!==endpoint.origin || archive.username || archive.password) throw new Error('Invalid project archive endpoint')
  }
  const exports=markedSource.match(/export\s*\{([^}]+)\}/)?.[1]
  const constructor=exports?.match(/(\w+)\s+as\s+Marked\b/)?.[1]
  if(!constructor) throw new Error('Cannot bundle the installed Markdown renderer')
  const renderer=markedSource.replace(/export\s*\{[^}]+\}\s*;?/,'')
  const zipper=options.archiveUrl?'undefined':`(()=>{const module={exports:{}};const exports=module.exports;${zipSource};return module.exports})()`
  const script=`(()=>{${renderer}\n(${projectShareBrowser.toString()})(new ${constructor}(),${zipper});})();`.replace(/<\/script/gi,'<\\/script')
  const title=normalizeShareTitle(options.title,snapshot.entry)
  const escape=(value:string)=>value.replace(/[&<>"\']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))
  const presentation=options.presentation && {themeId:options.presentation.themeId,documents:options.presentation.documents,warnings:options.presentation.warnings}
  const payload=JSON.stringify({snapshot,feedbackUrl:endpoint.href,title,presentation,archiveUrl:options.archiveUrl,publicationPending:options.publicationPending}).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')
  const nonce=crypto.randomUUID().replace(/-/g,'')
  const origin=endpoint.origin.replace(/&/g,'&amp;').replace(/"/g,'&quot;')
  const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; img-src data: https: http:; font-src data:; connect-src ${origin}; base-uri 'none'; form-action 'none'"><title>${escape(title)} · 只读</title>${options.presentation?.styleHead??''}<style>${menuStyles}

*{box-sizing:border-box}body{margin:0;padding:0;font:15px/1.7 system-ui,sans-serif;color:#242424;background:#fff;color-scheme:light dark}.layout{--panel-width:240px;display:flex;min-height:100vh}button,input,textarea{font:inherit}button{cursor:pointer}button:disabled{cursor:default;opacity:.5}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible{outline:2px solid #4a8bd6;outline-offset:2px}[hidden]{display:none!important}
#file-panel{width:var(--panel-width);flex-shrink:0;position:sticky;top:0;height:100vh;overflow:auto;display:flex;flex-direction:column;background:#f8f8f8;border-right:1px solid #e5e5e5;padding:48px 6px 10px}#files{overflow:auto;flex:1;min-height:0}#download-all{flex:none;margin-top:10px;text-align:left;border-top:1px solid #ddd;border-radius:0;padding:10px 12px}#file-toggle{position:fixed;top:10px;left:8px;z-index:21;width:30px;height:30px;padding:5px;display:grid;place-items:center;background:Canvas;box-shadow:0 1px 4px #0001}.files-open #file-toggle{left:calc(var(--panel-width) - 38px)}#file-toggle svg{width:20px;height:20px}.files-open #file-toggle .toggle-chevron{transform:translateX(24px) scaleX(-1)}#file-menu{position:fixed;z-index:30}.file-download-action{border:0;background:none;color:inherit;font:inherit;width:100%;text-align:left}.reader-button{border:0;border-radius:5px;background:transparent;color:inherit;padding:5px 8px;font-size:13px;white-space:nowrap}.reader-button:hover{background:#ededed}#files,#files ul{list-style:none;padding:0;margin:0}.file-row{display:flex;align-items:center;gap:4px;width:100%;min-height:28px;padding:4px 8px;border:0;border-radius:4px;background:transparent;color:inherit;font-size:13px;line-height:20px;text-align:left}.file-row:hover{background:#eaeaea}.file-row[aria-current=page]{background:#e2e9f2;color:#175eaa}.file-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-icon{width:15px;height:15px;flex:none;opacity:.75}.chevron{width:14px;height:14px;flex:none;transition:transform .12s}.file-row[aria-expanded=true] .chevron{transform:rotate(90deg)}
main{width:100%;min-width:0;flex:1;padding:18px 28px 100px 48px}.files-open main{padding-left:28px}#reader #document,#comments,#editor{width:100%;max-width:none;min-width:0;margin-left:0;margin-right:0}.toolbar{position:fixed;bottom:14px;right:18px;z-index:10;display:flex;gap:4px;align-items:center;flex-wrap:wrap;max-width:calc(100vw - 36px);padding:5px;background:Canvas;color:CanvasText;border:1px solid #8883;border-radius:8px;box-shadow:0 2px 12px #0001}.files-open .toolbar{max-width:calc(100vw - var(--panel-width) - 36px)}#collaboration-options summary{list-style:none}#collaboration-options summary::-webkit-details-marker{display:none}.secondary-actions{display:flex;flex-wrap:wrap;gap:4px;padding-top:6px}.toolbar input{width:125px;padding:4px 7px;border:1px solid #ddd;border-radius:5px;background:transparent;color:inherit;font-size:13px}#status{font-size:13px;color:#666;white-space:pre-wrap;position:fixed;bottom:70px;right:18px;z-index:10;max-width:min(600px,calc(100vw - 36px));max-height:30vh;overflow:auto;padding:6px 10px;border-radius:6px;background:Canvas;box-shadow:0 1px 8px #0002}#status:empty{display:none}#editor{display:block;width:100%;min-height:65vh;padding:14px;font:14px/1.6 ui-monospace,monospace;color:inherit;background:transparent;border:1px solid #ddd;border-radius:6px}#document{overflow-wrap:anywhere;min-width:0;outline-offset:5px}:where(#document) img{max-width:100%;height:auto}#document pre,#document .katex-display,#document .diagram-container,#document .mermaid,#document .dot{max-width:100%;overflow-x:auto}#document table{display:block;max-width:100%;overflow-x:auto}#comments blockquote{border-left:3px solid #ccc;margin:16px 0;padding-left:16px}#comments blockquote{white-space:pre-wrap}.unshared,.draft-diagram-note{color:#777}.draft-diagram-note{font:13px/1.6 system-ui,sans-serif;margin:8px 0}#file-backdrop{display:none}
@media(prefers-color-scheme:dark){body{background:#1c1c1e;color:#ddd}#file-panel{background:#222225;border-color:#353538}.reader-button:hover,.file-row:hover{background:#303034}.file-row[aria-current=page]{background:#303f54;color:#a8cdf8}.toolbar input,#editor{border-color:#444}#status,.unshared,.draft-diagram-note{color:#aaa}}
@media(max-width:650px){.layout{--panel-width:min(280px,85vw)}main,.files-open main{padding:14px 18px 110px 48px}.toolbar,.files-open .toolbar{gap:2px;max-width:calc(100vw - 24px);right:12px}.toolbar input{width:110px}#file-panel{position:fixed;inset:0 auto 0 0;z-index:20;width:min(280px,85vw);box-shadow:4px 0 25px #0003}#file-backdrop{display:block;position:fixed;inset:0;z-index:19;border:0;background:#0005}}
</style></head><body><div class="layout"><button id="file-backdrop" aria-label="关闭文件导航" hidden></button><nav id="file-panel" aria-label="文档" hidden><ul id="files"></ul><button id="download-all" class="reader-button">下载全部</button></nav><button id="file-toggle" class="reader-button" aria-controls="file-panel" aria-expanded="false" aria-label="展开文件导航" title="展开文件导航"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2" y="3" width="20" height="18" rx="2"/><path d="M8 3v18"/><path class="toggle-chevron" d="m12 9 3 3-3 3"/></svg></button><main id="reader"><div id="collaboration" class="toolbar" hidden><button id="edit" class="reader-button" disabled>编辑 Markdown</button><button id="annotate" class="reader-button" disabled>标注选文</button><button id="submit" class="reader-button" disabled>提交修改</button><details id="collaboration-options"><summary class="reader-button">更多</summary><div class="secondary-actions"><button id="baseline" class="reader-button" disabled>查看发布原文</button><input id="name" placeholder="署名（选填）" aria-label="署名"><button id="export" class="reader-button" disabled>导出草稿备份</button></div></details></div><div id="status" role="status" aria-live="polite"></div><article id="document" class="moraya-editor" tabindex="-1"></article><textarea id="editor" aria-label="Markdown" hidden></textarea><section id="comments" aria-label="我的标注"></section></main></div><div id="file-menu" class="menu-panel" role="menu" aria-label="文件操作" hidden><button id="download-file" class="menu-row file-download-action" role="menuitem">下载文件</button></div><script id="project-data" type="application/json">${payload}</script><script nonce="${nonce}">${script}</script></body></html>`
  if(new TextEncoder().encode(html).byteLength>25*1024*1024) throw new Error('分享包超过 25 MiB，请减少分享文件或资源')
  return html
}
