<script lang="ts">
  import { settings, saveSettings } from '../lib/settings.svelte'
</script>

<section class="block">
  <h3>OpenClaw</h3>

  <label class="row">
    <span class="lbl">Connect mode</span>
    <select bind:value={settings.openclaw.mode} onchange={() => saveSettings()}>
      <option value="auto">Auto-detect</option>
      <option value="host">Host (local UDS)</option>
      <option value="remote">Remote (via mdrelay)</option>
    </select>
  </label>

  <label class="row">
    <span class="lbl">Socket path</span>
    <input
      type="text"
      bind:value={settings.openclaw.socketPath}
      placeholder="~/.openclaw/mdeditor.sock"
      onchange={() => saveSettings()}
    />
  </label>

  <label class="row">
    <span class="lbl">Access token</span>
    <input
      type="password"
      bind:value={settings.openclaw.accessToken}
      placeholder="Auto-generated by OpenClaw"
      onchange={() => saveSettings()}
    />
  </label>

  <label class="row">
    <span class="lbl">Relay URL</span>
    <input
      type="text"
      bind:value={settings.openclaw.relayUrl}
      placeholder="wss://mdrelay.example.com"
      onchange={() => saveSettings()}
    />
  </label>

  <label class="row" style="margin-top: 6px;">
    <input
      type="checkbox"
      bind:checked={settings.openclaw.autoSyncBeforeResolve}
      onchange={() => saveSettings()}
    />
    Auto-sync before resolving chat links
  </label>
</section>

<style>
  .block {
    padding: 12px 0;
    border-top: 1px solid color-mix(in srgb, CanvasText 10%, transparent);
  }
  .block:first-of-type { border-top: 0; padding-top: 0; }
  h3 {
    margin: 0 0 8px 0;
    font-size: 13px;
    font-weight: 600;
  }
  .row { display: flex; gap: 8px; align-items: center; font-size: 13px; margin-bottom: 10px; }
  .row .lbl {
    width: 80px;
    flex-shrink: 0;
  }
  .row input[type="text"],
  .row input[type="password"],
  .row select {
    flex: 1;
    padding: 4px 8px;
    border-radius: 4px;
    border: 1px solid color-mix(in srgb, CanvasText 25%, transparent);
    background: Canvas;
    color: CanvasText;
    font-size: 13px;
  }
  .row input[type="checkbox"] { width: auto; }
</style>
