#!/usr/bin/env bash
# Regenerate the plugin v2 contract artifacts from the Rust source of truth.
# --check: fail if regeneration produces a diff (CI mode).
set -euo pipefail
cd "$(dirname "$0")/.."

cargo run --quiet --manifest-path plugin-protocol/Cargo.toml --bin gen-schema

mkdir -p src/lib/plugins/v2

# rpc.schema.json is a $defs-only container; pre-process it into a combined
# schema with hoisted definitions so json2ts can consume it via
# --unreachableDefinitions. RpcResponse internally uses #/definitions/RpcError
# (schemars draft-07), so we hoist all nested definitions to root level.
python3 - <<'PYEOF' > /tmp/rpc-combined.schema.json
import json
with open("protocol/schema/rpc.schema.json") as f:
    data = json.load(f)
combined = {"$schema": "http://json-schema.org/draft-07/schema#", "definitions": {}}
for key, schema in data["$defs"].items():
    clean_name = key.split("::")[-1]
    s = dict(schema)
    s.pop("$schema", None)
    inner_defs = s.pop("definitions", {})
    for iname, ischema in inner_defs.items():
        combined["definitions"][iname] = ischema
    combined["definitions"][clean_name] = s
print(json.dumps(combined, indent=2))
PYEOF

# Generate manifest types (clean, no post-processing needed)
MANIFEST_TYPES=$(npx json2ts --no-additionalProperties protocol/schema/manifest-v2.schema.json)

# Generate RPC types; strip:
#   1. The boilerplate eslint-disable + auto-generated comment header
#   2. The empty RpcCombinedSchema placeholder interface (root wrapper object)
RPC_TYPES=$(npx json2ts --no-additionalProperties --unreachableDefinitions /tmp/rpc-combined.schema.json \
  | python3 -c "
import sys, re
text = sys.stdin.read()
# Strip the top boilerplate header (eslint-disable + jsdoc comment block)
text = re.sub(r'/\* eslint-disable \*/\n/\*\*.*?\*/\n\n', '', text, count=1, flags=re.DOTALL)
# Strip the RpcCombinedSchema placeholder interface block entirely
text = re.sub(r'export interface RpcCombinedSchema \{[^}]*\}\n', '', text, flags=re.DOTALL)
print(text, end='')
")

{
  echo "/* AUTO-GENERATED by scripts/gen-plugin-protocol.sh — DO NOT EDIT."
  echo "   Source of truth: plugin-protocol/src/lib.rs */"
  echo "$MANIFEST_TYPES"
  echo "$RPC_TYPES"
} > src/lib/plugins/v2/protocol.gen.ts

if [[ "${1:-}" == "--check" ]]; then
  git diff --exit-code protocol/schema src/lib/plugins/v2/protocol.gen.ts \
    || { echo "❌ protocol artifacts out of date — run scripts/gen-plugin-protocol.sh"; exit 1; }
fi
echo "✓ protocol artifacts up to date"
