export type MessageKey = keyof typeof en

const en = {
  title: 'Meetings',
  subtitle: 'Speaker-attributed, time-coded transcripts in ssot/meetings',
  'action.migrate': 'Migrate from Hemory…',
  'action.refresh': 'Refresh',
  'action.close': 'Close',
  'action.back': 'Back to meetings',
  'action.choose': 'Choose Hemory folder…',
  'action.change': 'Choose another folder…',
  'action.preflight': 'Run preflight',
  'action.retry': 'Try again',
  'action.confirm': 'Start migration',
  'action.cancel': 'Stop after this meeting',
  'action.done': 'Done',
  'action.open': 'Open transcript',
  'library.empty': 'No meeting transcripts yet.',
  'library.emptyHint': 'Migrate a Hemory archive to begin, or add a transcript under ssot/meetings.',
  'library.loading': 'Loading meetings…',
  'library.speakers': '{count} speakers',
  'library.source': 'Source: {source}',
  'migration.title': 'Migrate from Hemory',
  'migration.subtitle': 'The source is read-only. Audio files are never copied or referenced.',
  'migration.source': 'Hemory source',
  'migration.sourceHint': 'Choose a Hemory root, user root, or conversation(s) folder.',
  'migration.detecting': 'Detecting layouts and users…',
  'migration.user': 'Hemory user',
  'migration.chooseUser': 'Choose a user',
  'migration.timezone': 'Historical timezone',
  'migration.timezoneHint': 'Use an IANA name such as Asia/Taipei. This is required only for timestamps without an offset.',
  'migration.mode': 'Scan mode',
  'migration.incremental': 'Incremental',
  'migration.incrementalHint': 'Imports everything on the first run; later runs process only new or changed meetings.',
  'migration.full': 'Full rescan',
  'migration.fullHint': 'Revalidates every source meeting without overwriting conflicts or deleting archived meetings.',
  'migration.planning': 'Checking transcripts and planning changes…',
  'migration.preflight': 'Preflight',
  'migration.preflightHint': 'No files have been written. Review every conflict or blocked item before continuing.',
  'migration.confirmTitle': 'Start this migration?',
  'migration.confirmBody': 'Each eligible meeting is committed independently. You can stop safely between meetings and resume later.',
  'migration.running': 'Migrating meetings…',
  'migration.progress': '{done} of {total} committed',
  'migration.stopping': 'Stopping after the current meeting…',
  'migration.result': 'Migration result',
  'migration.resultOk': 'The migration completed cleanly.',
  'migration.resultProblems': 'The migration completed with conflicts or blocked items. Nothing was overwritten.',
  'migration.noChanges': 'There are no meetings to create or update.',
  'migration.detectWarning': 'Detection warnings',
  'migration.audioExcluded': 'Audio excluded',
  'report.scanned': 'Scanned',
  'report.eligible': 'Eligible',
  'report.create': 'Create',
  'report.update': 'Update',
  'report.skip': 'Unchanged',
  'report.conflict': 'Conflict',
  'report.blocked': 'Blocked',
  'report.source_missing': 'Source missing',
  'report.excluded': 'Audio excluded',
  'report.committed': 'Committed',
  'report.details': 'Details',
  'report.sourcePath': 'Source',
  'report.targetPath': 'Target',
  'report.transcript': 'Transcript',
  'error.noVault': 'Configure a Vault before using Meetings.',
  'error.detect': 'Could not inspect this Hemory folder.',
  'error.plan': 'Preflight failed. No files were written.',
  'error.apply': 'Migration stopped. Completed meetings remain safely checkpointed.',
  'error.library': 'Could not load the meeting library.',
} as const

const zh: Partial<Record<MessageKey, string>> = {
  title: '会议记录', subtitle: '归档于 ssot/meetings 的带说话人、带时间码逐字稿',
  'action.migrate': '从 Hemory 迁移…', 'action.refresh': '刷新', 'action.close': '关闭',
  'action.back': '返回会议列表', 'action.choose': '选择 Hemory 目录…', 'action.change': '选择其他目录…',
  'action.preflight': '开始预检', 'action.retry': '重试', 'action.confirm': '开始迁移',
  'action.cancel': '完成当前会议后停止', 'action.done': '完成', 'action.open': '打开逐字稿',
  'library.empty': '还没有会议逐字稿。', 'library.emptyHint': '可以先迁移 Hemory 归档，或在 ssot/meetings 下加入逐字稿。',
  'library.loading': '正在读取会议…', 'library.speakers': '{count} 位说话人', 'library.source': '来源：{source}',
  'migration.title': '从 Hemory 迁移', 'migration.subtitle': '来源目录只读；音频文件不会被复制，也不会写入引用。',
  'migration.source': 'Hemory 来源', 'migration.sourceHint': '请选择 Hemory 根目录、用户目录或 conversation(s) 目录。',
  'migration.detecting': '正在检测目录布局和用户…', 'migration.user': 'Hemory 用户',
  'migration.chooseUser': '请选择用户', 'migration.timezone': '历史时区',
  'migration.timezoneHint': '请输入 IANA 时区，例如 Asia/Taipei；只有缺少 offset 的历史时间才需要。',
  'migration.mode': '扫描模式', 'migration.incremental': '增量',
  'migration.incrementalHint': '首次会自然导入全部；以后只处理新增或变化的会议。',
  'migration.full': '全量重扫', 'migration.fullHint': '重新校验全部来源，但仍不覆盖冲突，也不删除已归档会议。',
  'migration.planning': '正在校验逐字稿并生成迁移计划…', 'migration.preflight': '预检结果',
  'migration.preflightHint': '尚未写入任何文件。请先检查冲突和阻断项。',
  'migration.confirmTitle': '开始这次迁移？',
  'migration.confirmBody': '每个会议会独立提交；可以在会议边界安全停止，之后继续迁移。',
  'migration.running': '正在迁移会议…', 'migration.progress': '已提交 {done} / {total}',
  'migration.stopping': '将在当前会议完成后停止…', 'migration.result': '迁移结果',
  'migration.resultOk': '迁移已完成。', 'migration.resultProblems': '迁移完成，但仍有冲突或阻断项；没有覆盖任何内容。',
  'migration.noChanges': '没有需要新建或更新的会议。', 'migration.detectWarning': '检测警告',
  'migration.audioExcluded': '音频已排除', 'report.scanned': '已扫描', 'report.eligible': '可迁移',
  'report.create': '新建', 'report.update': '更新', 'report.skip': '未变化', 'report.conflict': '冲突',
  'report.blocked': '已阻断', 'report.source_missing': '来源缺失', 'report.excluded': '排除音频',
  'report.committed': '已提交', 'report.details': '明细', 'report.sourcePath': '来源',
  'report.targetPath': '目标', 'report.transcript': '逐字稿',
  'error.noVault': '请先配置知识库，再使用会议记录。', 'error.detect': '无法检查这个 Hemory 目录。',
  'error.plan': '预检失败，没有写入任何文件。', 'error.apply': '迁移已停止；已完成的会议仍安全保留并记录。',
  'error.library': '无法读取会议列表。',
}

let locale = 'en'

export function setLocale(value: string): void {
  locale = value.toLowerCase().startsWith('zh') ? 'zh' : 'en'
}

export function t(key: MessageKey, params: Record<string, string | number> = {}): string {
  let value = (locale === 'zh' ? zh[key] : undefined) ?? en[key]
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{${name}}`, String(replacement))
  }
  return value
}
