/* AUTO-GENERATED by scripts/gen-plugin-protocol.sh — DO NOT EDIT.
   Source of truth: plugin-protocol/src/lib.rs */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PluginKind = "native" | "wasm";

export interface ManifestV2 {
  activation: Activation;
  binary?: {
    [k: string]: string;
  };
  capabilities: string[];
  contributes?: Contributes;
  description?: string | null;
  engines: Engines;
  i18n?: {
    [k: string]: unknown;
  };
  id: string;
  idle_shutdown_seconds?: number | null;
  kind: PluginKind;
  manifest_version: number;
  name: string;
  request_timeout_seconds?: number | null;
  ui?: string | null;
  version: string;
}
export interface Activation {
  events: string[];
}
export interface Contributes {
  cli?: unknown[];
  context_menus?: unknown[];
  custom_editors?: unknown[];
  menus?: unknown[];
  settings?: {
    [k: string]: unknown;
  };
  windows?: unknown[];
}
export interface Engines {
  notemd: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "ActivateParams".
 */
export interface ActivateParams {
  event: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "ExecuteCommandParams".
 */
export interface ExecuteCommandParams {
  command: string;
  context: unknown;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "InitializeParams".
 */
export interface InitializeParams {
  data_dir: string;
  host_version: string;
  locale: string;
  plugin_root: string;
  protocol_version: number;
  theme: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "LogParams".
 */
export interface LogParams {
  message: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "RpcError".
 */
export interface RpcError {
  code: number;
  message: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "RpcRequest".
 */
export interface RpcRequest {
  id?: number | null;
  jsonrpc: string;
  method: string;
  params?: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "RpcResponse".
 */
export interface RpcResponse {
  error?: RpcError | null;
  id: number;
  jsonrpc: string;
  result?: unknown;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "ToastParams".
 */
export interface ToastParams {
  detail?: string | null;
  level: string;
  message: string;
}
