/* AUTO-GENERATED by scripts/gen-plugin-protocol.sh — DO NOT EDIT.
   Source of truth: plugin-protocol/src/lib.rs */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FileViewIcon = "generic" | "sparkle" | "clock";
export type FileViewScalar = string | number | boolean;
export type PluginKind = "native" | "wasm";

export interface ManifestV2 {
  activation: Activation;
  binary?: {
    [k: string]: string;
  };
  capabilities: string[];
  contributes?: Contributes;
  description?: string | null;
  engines: Engines;
  i18n?: {
    [k: string]: unknown;
  };
  id: string;
  idle_shutdown_seconds?: number | null;
  kind: PluginKind;
  manifest_version: number;
  name: string;
  request_timeout_seconds?: number | null;
  ui?: string | null;
  version: string;
}
export interface Activation {
  events: string[];
}
export interface Contributes {
  cli?: unknown[];
  context_menus?: unknown[];
  custom_editors?: unknown[];
  /**
   * Read-only views selected by declarative file rules; independent of file ownership.
   *
   * @maxItems 32
   */
  file_views?: FileViewContribution[];
  menus?: unknown[];
  settings?: {
    [k: string]: unknown;
  };
  tray?: TrayContribution[];
  windows?: WindowContribution[];
}
export interface FileViewContribution {
  entry: string;
  /**
   * Icon shown in the host's compact file-view switcher.
   */
  icon?: FileViewIcon;
  id: string;
  /**
   * Host-handled menu command that opens this view for the active file. ASCII [a-z0-9][a-z0-9._-]*, at most 128 characters; no process activation.
   */
  open_command?: string;
  priority?: number;
  /**
   * @minItems 1
   * @maxItems 32
   */
  selectors: [FileViewSelector, ...FileViewSelector[]];
}
/**
 * Selectors are ORed; fields within one selector are ANDed. Each value list is ORed; distinct frontmatter keys are ANDed.
 */
export interface FileViewSelector {
  /**
   * @minItems 1
   * @maxItems 32
   */
  file_extensions?: [string, ...string[]];
  /**
   * @minItems 1
   * @maxItems 32
   */
  file_name_patterns?: [string, ...string[]];
  frontmatter?: {
    [k: string]: FileViewScalar[];
  };
  /**
   * @minItems 1
   * @maxItems 32
   */
  path_patterns?: [string, ...string[]];
}
/**
 * 一个托盘启动项：宿主在菜单栏 tray 下拉里加一条,点击打开该插件的窗口。
 */
export interface TrayContribution {
  /**
   * 系统级全局快捷键，如 `"Cmd+Ctrl+I"`：宿主在启动时注册它，按下等同于点击 本托盘项；同时把它作为**显示用**加速键挂在托盘项右侧。
   *
   * 语法同 tauri-plugin-global-shortcut（`Cmd`/`Ctrl`/`Alt`/`Shift` + 键名， 大小写与修饰键顺序都不敏感）。解析失败、或组合已被别的 app 占用，都只记 日志：托盘项本身照常可点，插件照常加载。
   */
  accelerator?: string | null;
  /**
   * 托盘项文案；缺省用插件本地化名称（manifest `name` + `i18n.<locale>.name`）。
   */
  label?: string | null;
  /**
   * 进托盘下拉的哪一组。目前只认 [`TRAY_SECTION_CAPTURE`]（顶部捕获组： 快速笔记/每日笔记那一组，本项排在每日笔记之后、第一条分隔线之前）； 缺省 = 默认组（第一条分隔线之后、"显示主窗口"下面）。
   *
   * 刻意用 `Option<String>` 而不是 enum：这个字段是**开放取值**的，将来加一个 新组名不该让老宿主整份 manifest 解析失败（整个结构体是 `deny_unknown_fields`，一次解析失败 = 插件完全加载不出来）。宿主对不认识 的取值降级到默认组即可 —— 位置不理想，但插件仍然可用。
   */
  section?: string | null;
  /**
   * 要打开的窗口 id（须匹配某个 `contributes.windows[].id`）。
   */
  window: string;
}
export interface WindowContribution {
  entry: string;
  height: number;
  id: string;
  min_height?: number | null;
  min_width?: number | null;
  /**
   * contributes.menus 中命中此 command 的菜单项 = 打开本窗口（不走 command.execute）。
   */
  open_command?: string | null;
  singleton?: boolean;
  title?: string | null;
  width: number;
}
export interface Engines {
  notemd: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "ActivateParams".
 */
export interface ActivateParams {
  event: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "ExecuteCommandParams".
 */
export interface ExecuteCommandParams {
  command: string;
  context: unknown;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "InitializeParams".
 */
export interface InitializeParams {
  data_dir: string;
  host_version: string;
  locale: string;
  plugin_root: string;
  protocol_version: number;
  theme: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "LogParams".
 */
export interface LogParams {
  message: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "RpcError".
 */
export interface RpcError {
  code: number;
  message: string;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "RpcRequest".
 */
export interface RpcRequest {
  id?: number | null;
  jsonrpc: string;
  method: string;
  params?: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "RpcResponse".
 */
export interface RpcResponse {
  error?: RpcError | null;
  id: number;
  jsonrpc: string;
  result?: unknown;
}
/**
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "ToastParams".
 */
export interface ToastParams {
  detail?: string | null;
  level: string;
  message: string;
}
/**
 * 插件→宿主 `host.ui.post`：插件进程向自己的窗口推送消息。
 *
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "UiPostParams".
 */
export interface UiPostParams {
  payload: unknown;
  window_id: string;
}
/**
 * 宿主→插件 `ui.request`：UI 窗口请求自己的插件进程执行操作。
 *
 * This interface was referenced by `RpcCombinedSchema`'s JSON-Schema
 * via the `definition` "UiRequestParams".
 */
export interface UiRequestParams {
  method: string;
  params?: {
    [k: string]: unknown;
  };
}
